spring.application.name=asientos.user-ms
server.port=5011
jwt.secret=${JWT_SECRET}

spring.datasource.url=jdbc:postgresql://localhost:5432/UserServiceTicketMasterDB
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

spring.mvc.log-resolved-exception=true
logging.level.org.springframework.web=DEBUG


#SWAGGER

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
# Para mostrar la duración de las peticiones en la UI
springdoc.swagger-ui.display-request-duration=true



# Schema Registry (Puerto por defecto 8081)
spring.kafka.properties.schema.registry.url=http://localhost:8081

#kafka
spring.kafka.bootstrap-servers=localhost:9094



# Configuración del Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

# Configuración del Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.specific.avro.reader=true


# Configuracion del Circuit Breaker
spring.aop.proxy-target-class=true
resilience4j.circuitbreaker.configs.dbConfig.sliding-window-size=5
resilience4j.circuitbreaker.configs.dbConfig.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.dbConfig.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.configs.dbConfig.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.configs.dbConfig.register-health-map=true

#timeoutdame
spring.datasource.hikari.connection-timeout=1000


# EXCEPCIONES PARA QUE CIRCUIT BRACKER TOMA EN CUENTA
resilience4j.circuitbreaker.instances.dbConfig.record-exceptions=\
    org.springframework.transaction.CannotCreateTransactionException,\
    org.hibernate.exception.JDBCConnectionException,\
    java.net.ConnectException,\
    org.springframework.dao.DataAccessResourceFailureException